Turret
FRC4607/2020-CompBot pull request #15
Opened 2020-02-17 16:09 UTC by 22nadsup

This is the code from yesterday at Week Zero. Mostly autonomous, and start to lime light with the turret.

2020-02-18 15:47 UTC, ejmccalla commented on src/main/java/frc/robot/Robot.java
> +        PortForwarder.add( 5801, "10.46.7.1", 5801 );
What's this?

2020-02-18 15:50 UTC, ejmccalla commented on src/main/java/frc/robot/commands/Auto1.java
> +       while( System.currentTimeMillis() <= start + 3000 ) {}
This while loop is "blocking".  In this situation, blocking isn't what you want to be doing.  I expect if you actually run this code you'd see see a lot of messages from the motor safety class telling you that the motor outputs aren't being updated frequently enough.  Instead of using this blocking statement, use a timer instead.  Look at the seek timer I have in the hood subsystem as an example.

2020-02-18 15:53 UTC, ejmccalla commented on src/main/java/frc/robot/commands/TurretSpin.java
> +                mTurret.setOpenLoop( mTurret.mVision.getOutput() );
This is potentially dangerous and requires lots of testing to ensure you don't drive the turret past the hard stops.  I would suggest adding limit switches to the turret and hood which will protect the hardware while you're learning how to use the limelight for positional feedback.

2020-02-18 15:55 UTC, ejmccalla commented on src/main/java/frc/robot/lib/drivers/Limelight.java
> +public class Limelight {
This likely needs to be updated to support the latest Limelight firmware.  Do you have the latest Limelight firmware on the device?

2020-02-18 15:58 UTC, ejmccalla commented on src/main/java/frc/robot/subsystems/Drivetrain.java
> +
You're function inputs, although correct for data type, are not being used logically correct.  For example, there is not CAN timeout.  Instead, this input is RPM.  Don't just make changes to get the "error" to go away within VSCode because that only catches syntax and similar errors.  It's on you to make sure you read and understand the API.  If you actually ran this code on the robot, I'd expect the drivetrain to be severely under-powered and you'd be scratching your head for awhile on this one.

2020-02-18 16:02 UTC, ejmccalla commented on src/main/java/frc/robot/Robot.java
> +        mRobotContainer.StartLimelight();
Muti-threaded programming isn't easy.  I suggest putting the vision code in it's own subsystem.

https://github.com/STMARobotics/frc-7028-2020/blob/master/src/main/java/frc/robot/subsystems/LimelightSubsystem.java

2020-02-18 16:03 UTC, ghost requested changes
PR's should only be done when you have code that has been compiled and tested on the robot.  Until that happens, develop in the branch.

I left several comments.

2020-02-18 21:50 UTC, 22nadsup commented on src/main/java/frc/robot/Robot.java
> +        PortForwarder.add( 5801, "10.46.7.1", 5801 );
That's for the limelight

2020-02-18 21:55 UTC, 22nadsup commented on src/main/java/frc/robot/commands/Auto1.java
> +       while( System.currentTimeMillis() <= start + 3000 ) {}
We won't be using this autonomous anyways, but that explains why the drive train wouldn't move.

2020-02-18 21:56 UTC, 22nadsup commented on src/main/java/frc/robot/commands/TurretSpin.java
> +                mTurret.setOpenLoop( mTurret.mVision.getOutput() );
Oh trust me all the open loops are dangerous, but we didn't even give anyone the option to test it on the Turret.

2020-02-18 22:09 UTC, ejmccalla commented on src/main/java/frc/robot/subsystems/Flywheel.java
> +        mMaster.configContinuousCurrentLimit( 6, CURRENT_LIMIT.RPM_LIMIT );
The Talon current limits is different from the Spark current limiting....brushed motor vs. brushless.  I think you need to seek out some guidance on how to setup these limits.

2020-02-18 23:11 UTC, DianaBellefeuille commented on src/main/java/frc/robot/lib/drivers/Limelight.java
> +public class Limelight {
latest firmware is on the LL currently on the robot, the spares have yet to be updated

2020-02-18 23:12 UTC, DianaBellefeuille commented on src/main/java/frc/robot/Robot.java
> +        mRobotContainer.StartLimelight();
Like instead of having the limelight as a driver?

2020-02-19 00:50 UTC, ejmccalla commented on src/main/java/frc/robot/Robot.java
> +        mRobotContainer.StartLimelight();
No.  Don't use the vision controller.  This uses the notifier class and that is what will make it multi-threaded.

2020-02-19 00:55 UTC, ejmccalla commented
Instead of trying to get the Limelight working, I suggest getting the current limiting working.  Right now, you have too many irons in the fire.

2020-03-04 18:47 UTC, AnthonyGuck commented on src/main/java/frc/robot/Main.java
> +    private Main () {
Do you know that putting a space between main and the parenthesis does not change the function of the code?

2020-03-04 18:52 UTC, DianaBellefeuille commented on src/main/java/frc/robot/commands/HoodDrive.java
> +        double xHoodR = ( 0.2 * mOperatorXbox.getRawAxis( 5 ) );
What is the difference between xHood and xHoodR? It looks like xHoodR is just the reverse of xHood, but you should specify in a comment and say why we need 2 different variables

2020-03-04 18:56 UTC, DianaBellefeuille requested changes
We should test this code on the robot and then merge so that the master branch is up to date with the working competition code.

2020-03-05 21:46 UTC, DianaBellefeuille approved these changes
We will work more on hood later

2020-03-05 21:46 UTC, merged